### ISSUE TITLE
Unable to open Debian package (.deb).

### ISSUE THREAD

**Issue by babam86** [mate-desktop/engrampa#156] opened 2016-10-12 03:29 UTC
Engrampa 14.1 is unable to open Debian package (.deb).

**Comment by sc0w** [comment] 2016-10-12 10:20
what is the file?

**Comment by sc0w** [comment] 2017-01-11 14:53
ok, I can confirm now

I see for example, the engrampa's deb package:

![engrampadeb](https://cloud.githubusercontent.com/assets/7734191/21853041/bd2ffff6-d815-11e6-85ad-930b94fb1290.png)

and the expected, with file-roller 3.22.2

![filerollerdeb](https://cloud.githubusercontent.com/assets/7734191/21853045/c32b068a-d815-11e6-943c-dbc31525bcb2.png)

here is the deb file for testing:

https://packages.debian.org/stretch/amd64/engrampa/download

**Comment by sc0w** [comment] 2017-01-11 21:29
on file-roller works because it uses libarchive

the same .deb file on file-roller without libarchive, works same than engrampa

**Comment by sc0w** [comment] 2017-01-13 22:37
engrampa can open the deb files, but it doesn't show the three main files and we can't extract individually the three files

about the **.deb** format:
https://en.wikipedia.org/wiki/Deb_%28file_format%29

well, after my investigations, I think engrampa works as expected, because it uses **dpkg-deb** to do the job

If the user doesn't have **dpkg-deb** , engrampa uses **ar** and it works like file-roller, showing the three files

this is the structure (all in one):

![engrampadetails](https://cloud.githubusercontent.com/assets/7734191/21908808/af88a802-d915-11e6-94e5-533d66ba7fed.png)

and file-roller with its three files:

![filerollerdeb](https://cloud.githubusercontent.com/assets/7734191/21853045/c32b068a-d815-11e6-943c-dbc31525bcb2.png)

I have a fix to work like file-roller, giving **ar** priority over **dpkg-deb**, but I think is more usefully to have all the files on the same window

so, engrampa can open .deb files, I will unconfirm this issue

@babam86 if you can't open a .deb file, please tell us which file

**Comment by flexiondotorg** [comment] 2017-01-18 00:41
Engrampa can open deb file, as illustrated above. Closing this.

**Closed by flexiondotorg** 2017-01-18 00:41 UTC
Labels: unconfirmed
